### ISSUE TITLE
Call for participitation?

### ISSUE THREAD

**Issue by rnestler** [SwissPy/SwissPy.github.io#17]
According to https://twitter.com/pythonsummit/status/1196452505317789696 from 2019-11-18 there will be "A call for participation will be published in a few weeks."
Is it already over or hasn't it yet been published? I can't find anything on https://www.python-summit.ch/

**Comment by rodolphoeck** [comment]
Hello @rnestler, the CFP has not been published yet.
We're sorry for the delay and we plan on doing so soon.
Thank you!

**Comment by rodolphoeck** [comment]
The CfP is now open: https://www.python-summit.ch/cfp/
We'll make a public announcement today as well.

Thank you!
